/**
 * The suggestions under the prompt box, copied from `frontend/app.js:3713`.
 *
 * One per group is offered at a time, so the five on screen span mood,
 * activity, era, genre and tempo rather than five variations of one idea.
 *
 * Prompt text lives in one file, per `CLAUDE.md`: these are words a model
 * eventually reads, and spreading them across the components that send them
 * is worse than the size of this one.
 */

/** Five groups: mood, activity, era, genre, tempo. */
export const PROMPT_GROUPS: readonly (readonly string[])[] = [
  /* Mood / Energy */
  [
    'Happy but not annoying about it',
    'Sad in a way that feels good',
    'Angry, the productive kind',
    'Euphoric, peak of a good night',
    'Dreamy and slightly out of focus',
    'Quiet devastation, keep moving',
    'Wistful, not wallowing',
    'Warm like the end of something good',
    "Tense, something's about to happen",
    'Bittersweet and okay with it',
    'Dark but not hopeless',
    'Hopeful, first day of something',
    'Numb, just need the room filled',
    'Giddy, almost embarrassingly so',
    'Restless, needs to match the mood',
    'Nostalgic for something nameless',
    'Melancholy with good bones',
    'Calm but not sleepy',
    'Raw and unpolished',
    'The comedown after something great',
  ],
  /* Activity / Context */
  [
    "Cooking slowly, no one's waiting",
    'Late night drive, no destination',
    'Last hour before a deadline',
    'Long run, needs to pull you forward',
    'Pre-game, getting the nerve up',
    'Dinner party winding down well',
    'Highway, windows cracked',
    'Deep work, two hours, no surfacing',
    'Getting ready, building confidence',
    'Decompressing after a hard week',
    'Solo night in, no explanation',
    'Long flight, trying not to think',
    'Cleaning like you mean it',
    'Slow afternoon in the garden',
    'Walk home after something big',
    'After the party, just the dishes',
    'Slow dance, no one watching',
    'First coffee, easing in gently',
    "Walking a city you don't know",
    'BBQ that peaked an hour ago',
  ],
  /* Era / Decade */
  [
    '1970s soul, windows down',
    'Classic rock with actual grit',
    '1983, in the best possible way',
    'Early 90s indie, four-track raw',
    'Late 90s, before it all sped up',
    '1967, before psychedelia curdled',
    '2004 indie rock, blog-era peak',
    'Motown, hits and deep cuts both',
    '80s R&B, lush and unhurried',
    '90s hip hop, NY and LA both',
    "1972, recorded in someone's house",
    'Early 2010s, last of guitar bands',
    'British Invasion, no novelty acts',
    '1957 jazz, smoke and late hours',
    '2003 pop-punk, embarrassingly good',
    'Outlaw country, pre-mainstream',
    '80s post-punk, angular and cold',
    '90s rave, before it was a brand',
    'Krautrock, motorik and meditative',
    'Late 80s hip hop, the invention',
  ],
  /* Genre / Style */
  [
    'Jazz, late and smoky, no hurry',
    'Ambient, no pulse, just texture',
    'Punk, fast and under two minutes',
    'Soul with real weight behind it',
    'Metal that means what it says',
    'Acoustic folk, campfire honest',
    'Reggae, slow afternoon, no agenda',
    'Electronic, precise and cold',
    'Blues that invented everything else',
    'Country that earns the emotion',
    'Afrobeat, propulsive and communal',
    'Gospel with real conviction',
    'Indie pop, bright and aching',
    'Hardcore with something to say',
    'Bossa nova, unhurried and warm',
    'Lo-fi hip hop, dusty and patient',
    'Post-rock that earns its ending',
    'Disco, uncut and unapologetic',
    'Americana with dirt on it',
    'Shoegaze, loud and interior',
  ],
  /* Tempo / Danceability */
  [
    'Slow, nothing is rushing anywhere',
    'Midtempo groove, head nodding only',
    "Full energy, don't let up",
    'Dance floor, 120 BPM minimum',
    'Half-tempo, barely moving',
    'Builds slow, earns the drop',
    'Upbeat without being relentless',
    'Shuffling, laidback swing feel',
    'Relentless, no room to breathe',
    'Hypnotic, same thing, slight shifts',
    'Short and punchy, keep moving',
    'Slow burn that actually pays off',
    'Danceable, room for conversation',
    'Fast and slightly out of control',
    'Gentle pulse, background presence',
    'Syncopated and playful',
    'Doom tempo, slow and heavy',
    'Bouncy and major key, unashamed',
    'Sparse, lots of space in it',
    'Peaks and valleys, earns the quiet',
  ],
]
